In [1]:
import numpy as np
from ReplayBuffer import ReplayBuffer
from TD3 import TD3
from Critic import Critic
from Actor import Actor
import torch.nn as nn
import torch
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler


In [2]:
state_dim = 6
action_dim = 19
max_time = 10
max_action = 500

In [3]:
rb = ReplayBuffer(state_dim,action_dim)

In [4]:
policy = TD3(state_dim,action_dim,max_time,max_action)

In [5]:
for i in range(100):
    state = np.arange(6)
    action = np.arange(19)
    nxt_state = np.arange(6)
    reward = np.random.uniform(1000)
    rb.store(state,action,nxt_state,reward)

In [6]:
state, action, nxt_state, reward = rb.sample(32)

In [7]:
state[0]

array([0., 1., 2., 3., 4., 5.])

In [8]:
device = "cpu"

In [9]:
state = torch.FloatTensor(state).to(device)
action = torch.FloatTensor(action).to(device)
nxt_state = torch.FloatTensor(nxt_state).to(device)
reward = torch.FloatTensor(reward).to(device)

In [10]:
policy.train(rb,1,10)

tensor([401.5938, 197.4934, 460.8431, 197.4934, 799.0272, 348.5472, 360.2241,
        134.5787, 371.7381, 326.3681])
tensor([[401.5938],
        [197.4934],
        [460.8431],
        [197.4934],
        [799.0272],
        [348.5472],
        [360.2241],
        [134.5787],
        [371.7381],
        [326.3681]])
tensor([[0.1882],
        [0.1882],
        [0.1882],
        [0.1882],
        [0.1882],
        [0.1882],
        [0.1882],
        [0.1882],
        [0.1882],
        [0.1882]], grad_fn=<AddmmBackward0>)
tensor([[-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330],
        [-0.0330]], grad_fn=<AddmmBackward0>)
